version: "3.9"
services:
  app-repo:
    container_name: app-repo
    image: fjcvtcs/esc-teams-pub:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "3007:3007"
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app-repo
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: beep
      MONGO_INITDB_ROOT_PASSWORD: beepbeep123
      MONGO_INITDB_DATABASE: TeamsUserDB

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: beep
      ME_CONFIG_MONGODB_ADMINPASSWORD: beepbeep123
      ME_CONFIG_MONGODB_URL: mongodb://beep:beepbeep123@mongodb:27017/
    depends_on:
      - mongodb


  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: "no"   # never start certbot automatically
    depends_on:
      - "nginx"
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email 19980321lsr@gmail.com -d api-dev.veriform.ml --agree-tos
