version: "3.9"
services:
  app-repo:
    container_name: app-repo
    image: fjcvtcs/esc-teams:latest
    restart: unless-stopped
    ports:
      - "3007:3007"
    env_file:
      - .env


  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx_step1.conf:/etc/nginx/nginx.conf
